name: Docker Image node


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
      

    runs-on: self-hosted
    steps:
    
    - name: build_push_tag of develop
 
      env:      
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      
     
      run: |
            
             docker login -u $USERNAME -p $PASSWORD
             docker build -t firoj0786/node:${{ github.sha }} -f Dockerfile .  
             docker push firoj0786/node:${{ github.sha }}
         
             
  deploy:
 
    runs-on: self-hosted
    steps:
    
    - name: deploy app2
 
      env:
       PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      run: |
      
              docker login -u $USERNAME -p $PASSWORD
              docker build -t firoj0786/node:${{ github.sha }} -f Dockerfile .   
              docker push firoj0786/node:${{ github.sha }}
              docker-compose  up -d 
